import {StyleSheet} from 'react-native';
export const styles = StyleSheet.create({
  containerstyle: {
    flex: 1,
    backgroundColor: '#FAFAFA',
    paddingHorizontal: 20,
  },
  titletext: {
    color: '#171717',
    fontSize: 16,
    fontFamily: 'Manrope-SemiBold',
    marginVertical: 8,
  },
  text1: {
    fontSize: 12,
    fontFamily: 'Manrope-Medium',
    textAlign: 'center',
    color: '#171717',
  },
  filterContainer: {
    width: '13%',
    height: 40,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E8E8E8',
    borderRadius: 8,
    justifyContent: 'center',
  },
  topContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginVertical: 10,
  },
  card: {
    backgroundColor: '#fff',
    width: '100%',
    paddingHorizontal: 20,
    borderWidth: 0.7,
    borderColor: '#E8E8E8',
    borderRadius: 10,
    paddingBottom: 20,
    marginBottom: 100,
  },
  rectangleButton: {
    marginRight: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    borderColor: '#0E0E0F',
    marginTop: 10,
    alignSelf: 'center',
    paddingVertical: 6,
    paddingHorizontal: 20,
  },
  listContents: {
    flexDirection: 'row',
    width: '100%',
    flexWrap: 'wrap',
    alignItems: 'center',
  },
  footer: {
    position: 'absolute',
    left: 20,
    right: 20,
    bottom: 20,
  },
  grayContainer: {
    width: '100%',
    height: 75,
    backgroundColor: '#0C0C0C26',
    marginTop: 15,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
